### ISSUE TITLE
Remove existing tracked sqlite and media files

### ISSUE THREAD

**Issue by KaratasFurkan** [ozkseyma/hipogram#6]
We added these to gitignore and they will be ignored from now on but the existing ones should be removed too. I don't remember how to do that, can you search it? As far as I remember, there was a git command to remove some files from git tracking.

**Comment by KaratasFurkan** [comment]
Note: You can make these changes from the same branch, since it has the same context and it recently merged.

**Comment by seymaozukanar** [comment]
> 
I found the following command for this issue: git rm --cached.

**Comment by KaratasFurkan** [comment]
Does it create any git diff? (Does git status shows anything?) If not, I guess you need to delete the files and push those (delete) changes (as a new PR).

**Comment by KaratasFurkan** [comment]
But if you delete the files your local db and images will gone too. Let's find a better way, I will search this too.

**Comment by KaratasFurkan** [comment]
> Does it create any git diff? 

I tried your command and it creates git diff without deleting actual files, so it's correct. Let's do this and commit & push it to `3-sqlite-gitignore` branch, and open a new PR.
